config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :card_pages

  get '/mednews', to: 'mednews#mednews', as: :mednews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  # belongs_to :card_page
end

app/models/card_page.rb
class CardPage < ApplicationRecord
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/card_pages_controller.rb
class CardPagesController < ApplicationController
  before_action :set_card_page, only: [:show, :edit, :update, :destroy]

  # GET /card_pages
  # GET /card_pages.json
  def index
    @card_pages = CardPage.all
  end

  # GET /card_pages/1
  # GET /card_pages/1.json
  def show
  end

  # GET /card_pages/new
  def new
    @card_page = CardPage.new
  end

  # GET /card_pages/1/edit
  def edit
  end

  # POST /card_pages
  # POST /card_pages.json
  def create
    @card_page = CardPage.new(card_page_params)

    respond_to do |format|
      if @card_page.save
        format.html { redirect_to @card_page, notice: 'Card page was successfully created.' }
        format.json { render :show, status: :created, location: @card_page }
      else
        format.html { render :new }
        format.json { render json: @card_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_pages/1
  # PATCH/PUT /card_pages/1.json
  def update
    respond_to do |format|
      if @card_page.update(card_page_params)
        format.html { redirect_to @card_page, notice: 'Card page was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_page }
      else
        format.html { render :edit }
        format.json { render json: @card_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_pages/1
  # DELETE /card_pages/1.json
  def destroy
    @card_page.destroy
    respond_to do |format|
      format.html { redirect_to card_pages_url, notice: 'Card page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_page
      @card_page = CardPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_page_params
      params.require(:card_page).permit(:title, :h1, :body, :cards)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:title, :body)
    end
end

app/controllers/mednews_controller.rb
class MednewsController < ApplicationController
  def mednews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_pages_helper.rb
module CardPagesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/card_pages/_form.html.erb
<%= form_with(model: card_page, local: true) do |form| %>
  <% if card_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_page.errors.count, "error") %> prohibited this card_page from being saved:</h2>

      <ul>
      <% card_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :h1 %>
    <%= form.text_field :h1 %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.number_field :card_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/card_pages/edit.html.erb
<h1>Editing Card Page</h1>

<%= render 'form', card_page: @card_page %>

<%= link_to 'Show', @card_page %> |
<%= link_to 'Back', card_pages_path %>

app/views/card_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Card Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>H1</th>
      <th>Body</th>
      <th>Cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_pages.each do |card_page| %>
      <tr>
        <td><%= card_page.title %></td>
        <td><%= card_page.h1 %></td>
        <td><%= card_page.body %></td>
        <td><%= card_page.cards %></td>
        <td><%= link_to 'Show', card_page %></td>
        <td><%= link_to 'Edit', edit_card_page_path(card_page) %></td>
        <td><%= link_to 'Destroy', card_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card Page', new_card_page_path %>

app/views/card_pages/new.html.erb
<h1>New Card Page</h1>

<%= render 'form', card_page: @card_page %>

<%= link_to 'Back', card_pages_path %>

app/views/card_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card_page.title %>
</p>

<p>
  <strong>H1:</strong>
  <%= @card_page.h1 %>
</p>

<p>
  <strong>Body:</strong>
  <%= @card_page.body %>
</p>

<p>
  <strong>Cards:</strong>
  <%= @card_page.cards %>
</p>

<%= link_to 'Edit', edit_card_page_path(@card_page) %> |
<%= link_to 'Back', card_pages_path %>

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= card.body %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @card.body %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Medportal" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector:'textarea'});</script>

    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:wght@500&family=Rubik:ital,wght@0,400;0,500;0,700;1,400&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mednews/mednews.html.erb
<header>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-10 col-lg-3 d-flex align-items-center">
        <button class="menu-toggle" type="button" data-toggle="collapse" data-target="#navbar">
          <img src="" alt="">
        </button>
        <%= link_to image_tag("logo.png"), mednews_path, class: 'logo', alt: '' %>
      </div>
      <div class="col-2 col-lg-9 d-flex align-items-center">
        <nav class="navbar navbar-expand-lg d-none d-lg-flex">
          <div class="collapse navbar-collapse" id="navbar">

            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to 'Новости', '/', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Энциклопедия ', '/', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Клиники москвы ', '/', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Блоги', '/', class: "nav-link" %>
              </li>
            </ul>
          </div>
        </nav>
        <button type="button">
          <%= image_tag "magnify.svg", alt: '' %>
        </button>
      </div>
    </div>
  </div>
</header>

<div class="top-banner">
  <div class="container">
    <!-- Убираем у <a> style, добавляем изображению путь -->
    <a class="d-block" href="#" style="opacity:.2;background:#000;height:100px;">
      <!--img src="#" alt=""-->
    </a>
  </div>
</div>
<div class="container title-block">
  <div class="row small">
    <div class="col-6 d-block d-lg-none">
      <%= image_tag "note.svg", alt: '' %>
    </div>
    <div class="col-6 col-lg-12 d-flex flex-column flex-lg-row align-items-start justify-content-end align-items-lg-center">
      <div class="d-flex blue mr-4">
        <%= image_tag "card-text-outline.svg", class: 'mr-2', alt: '' %>
        15 карточек
      </div>
      <div class="d-flex gray mt-3 mt-lg-0">
        <%= image_tag "timer-sand.svg", class: 'mr-2', alt: '' %>
        8 минут
      </div>
      <div class="d-flex ml-lg-auto mt-3 mt-lg-0 gray">
        <%= image_tag "calendar.svg", class: 'd-block d-lg-none mr-2', alt: '' %>
        29 ноября 2019
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <h1>Говорят, витамин D нужно принимать круглый год и он защитит от рака, инфаркта и вообще почти всех болезней. А как на самом деле?</h1>
      <em>Длинная зима, инстаграм-блогеры и даже врачебные организации активно подталкивают людей к тому, чтобы те принимали витамин D. Причем иногда в очень больших дозировках.</em>
    </div>
    <div class="d-none d-lg-block col-lg-2 text-center">
      <%= image_tag "note.svg", alt: '' %>
    </div>
  </div>
</div>
<div class="questions">
  <div class="container">
    <div class="row">
      <div class="d-none d-lg-block col-lg-4">
        <ul class="questions-list">
          <li>
            <span class="num">1</span> Что случилось?
          </li>
          <li>
            <span class="num">2</span> Дефицит — это сколько?
          </li>
          <li>
            <span class="num">3</span> Чем опасен дефицит витамина D?
          </li>
          <li>
            <span class="num">4</span> Значит, препараты с витамином D вообще не нужны?
          </li>
          <li>
            <span class="num">5</span> То есть можно на всякий случай для профилактики рахита и остеомаляции принимать витамин D?
          </li>
          <li>
            <span class="num">6</span> Но вы же сказали, что в России почти у всех дефицит. Как его избежать?
          </li>
          <li>
            <span class="num">7</span> Может, мне надо принимать такие препараты?
          </li>
          <li>
            <span class="num">8</span> А не стоит ли на всякий случай принять дозу побольше?
          </li>
          <li>
            <span class="num">9</span> Значит, из-за солнца тоже можно получить передозировку?
          </li>
          <li>
            <span class="num">10</span> Если принимать витамин D, то в каком виде? Капли? Таблетки? Мармеладные мишки?
          </li>
          <li>
            <span class="num">11</span> Что за активная форма?
          </li>
          <li>
            <span class="num">12</span> А еще говорят, что витамины D и K надо принимать вместе для большего эффекта. Правда?
          </li>
          <li>
            <span class="num">13</span> А может, лучше просто сходить в солярий?
          </li>
          <li>
            <span class="num">14</span> Но вдруг у меня правда серьезный дефицит витамина D? Может, мне сдать анализ?
          </li>
          <li>
            <span class="num">15</span> Так принимать витамин D или нет?
          </li>
        </ul>
      </div>
      <div class="col-lg-8">
        <div class="question-title">1. Что случилось?</div>
        <div class="question-answer">
          <p>Длинная зима, инстаграм-блогеры и даже врачебные организации активно подталкивают людей к тому, чтобы те принимали витамин D. Причем иногда в очень больших дозировках.</p>
          <p>Он попадает в организм только с некоторыми продуктами и образуется в коже под воздействием солнечных лучей. Поэтому считается, что почти у всех людей, живущих в России, наверняка есть его дефицит.</p>
          <a href="#" class="share">
            <%= image_tag "share-variant.svg", alt: '' %>
          </a>
        </div>
        <div class="question-title">2. Дефицит — это сколько?</div>
        <div class="question-answer">
          <p>В России уровень витамина D от 20 до 29,9 нг/мл (от 50 до 75 нмоль/л) расценивается как недостаточность, а ниже 20 нг/мл (50 нмоль/л) — как дефицит.</p>
          <p>Но эта норма — предмет большого спора. По некоторым данным, при уровне меньше 20 нг/мл (50 нмоль/л) может развиваться остеопороз, повышаться риск переломов и падений у людей старшего возраста. Но в большинстве случаев при уровне 15–20 нг/мл никаких симптомов нет.</p>
          <p>Правда, другие зарубежные организации, как и российские, говорят, что норма — это 30 нг/мл (75 нмоль/л). Однако, возможно, на такой интерпретации результатов исследований сказался конфликт интересов.</p>
          <a href="#" class="share">
            <%= image_tag "share-variant.svg", alt: '' %>
          </a>
        </div>
        <div class="question-title">3. Чем опасен дефицит витамина D?</div>
        <div class="question-answer">
          <p>Во многих случаях у людей с дефицитом витамина D наблюдаются повышенные риски развития онкологических, сердечно-сосудистых, инфекционных и многих других заболеваний. Но о том, что причинно-следственная связь точно установлена, говорить рано.</p>
          <p>Исследования показывают, что дополнительный прием витамина D в форме лекарств или биологически активных добавок далеко не всегда эффективен.</p>
          <a href="#" class="share">
            <%= image_tag "share-variant.svg", alt: '' %>
          </a>
        </div>
        <div class="question-title">4. Значит, препараты с витамином D вообще не нужны?</div>
        <div class="question-answer">
          <p>Самые надежные данные об эффективности витамина D есть в отношении здоровья костей. Он участвует во всасывании кальция и фосфора, которые влияют на рост и минеральную плотность костей. И, строго говоря, доказано лишь то, что дефицит витамина D проявляется в проблемах с костями и мышцами: могут возникнуть рахит (у детей) и остеомаляция (у детей и взрослых). При этих состояниях кости становятся «мягкими» или хрупкими, они болят, деформируются, возникают переломы, а мышцы слабеют.</p>
          <p>Дополнительный прием витамина D помогает изменить ситуацию — но только если человек уже болеет. А вот исследований хорошего качества, которые бы показали, что препараты эффективны и в профилактике, пока недостаточно. Хотя логика в этом предположении, безусловно, есть.</p>
          <a href="#" class="share">
            <%= image_tag "share-variant.svg", alt: '' %>
          </a>
        </div>
        <div class="answers-bottom">
          <div class="gray">Константин Константинопольский</div>
          <ul>
            <li class="gray">
              <%= image_tag "eye.svg", alt: '' %> 3 548
            </li>
            <li>
              <a href="#">
                <%= image_tag "facebook.svg", alt: '' %>
              </a>
            </li>
            <li>
              <a href="#">
                <%= image_tag "vk.svg", alt: '' %>
              </a>
            </li>
            <li>
              <a href="#">
                <%= image_tag "odnoklassniki.svg", alt: '' %>
              </a>
            </li>
            <li>
              <a href="#">
                <%= image_tag "twitter.svg", alt: '' %>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="tag-anons">
    <p class="block-title">Подборка по тегу</p>
    <div class="row">
      <?php for($i = 0; $i < 2; $i++) { ?>
      <div class="col-lg-3">
        <a href="#">
          <%= image_tag "img.png", alt: '' %>
        </a>
        <p class="title">
          <a href="#">Киберхондрия - новая ипохондрия. Как перестать гуглить свои симптомы?</a>
        </p>
        <p>Симптомы заболевания - периодическая лихорадка и воспаление лимфоузлов</p>
        <div class="d-block d-lg-none">
          <a class="read-more" href="#">Читать статью</a>
          <hr>
        </div>
      </div>
      <?php } ?>
      <div class="col-lg-3">
        <a href="#">
          <%= image_tag "img.png", alt: '' %>
        </a>
        <p class="title">
          <a href="#">Киберхондрия - новая ипохондрия. Как перестать гуглить свои симптомы?</a>
        </p>
        <p>Симптомы заболевания - периодическая лихорадка и воспаление лимфоузлов</p>
        <div class="d-block d-lg-none">
          <a class="read-more" href="#">Читать статью</a>
        </div>
      </div>
      <div class="col-lg-3 d-none d-lg-block">
        <a href="#">
          <%= image_tag "img.png", alt: '' %>
        </a>
        <p class="title">
          <a href="#">Киберхондрия - новая ипохондрия. Как перестать гуглить свои симптомы?</a>
        </p>
        <p>Симптомы заболевания - периодическая лихорадка и воспаление лимфоузлов</p>
      </div>
    </div>
  </div>
  <div class="small-anons">
    <p class="block-title">Подборка с мелкими анонсами</p>
    <?php for($a = 0; $a < 3; $a++) { ?>
    <div class="row">
      <?php for($i = 0; $i < 2; $i++) { ?>
      <div class="col-lg-6">
        <div class="item">
          <a href="#" class="img">
            <%= image_tag "img.png", alt: '' %>
          </a>
          <div>
            <p class="blue">ЭТО ТЭГ СТАТЬИ</p>
            <p class="title">
              <a href="#">Обострение астмы связали с микробиомом дыхательных путей</a>
            </p>
            <p class="d-none d-lg-block mb-0">Присутствие стрептококков и моракселл часто сопровождало ухудшение состояния пациентов</p>
          </div>
        </div>
      </div>
      <?php } ?>
    </div>
    <?php } ?>
    <div class="row">
      <div class="col-lg-6">
        <div class="item">
          <a href="#" class="img">
            <%= image_tag "img.png", alt: '' %>
          </a>
          <div>
            <p class="blue">ЭТО ТЭГ СТАТЬИ</p>
            <p class="title">
              <a href="#">Обострение астмы связали с микробиомом дыхательных путей</a>
            </p>
            <p class="d-none d-lg-block mb-0">Присутствие стрептококков и моракселл часто сопровождало ухудшение состояния пациентов</p>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="item bg-blue">
          <a href="#" class="img">
            <%= image_tag "img.png", alt: '' %>
          </a>
          <div>
            <p class="blue">Реклама</p>
            <p class="title">
              <a href="#">Обострение астмы связали с микробиомом дыхательных путей</a>
            </p>
            <p class="d-none d-lg-block mb-0">Присутствие стрептококков и моракселл часто сопровождало ухудшение состояния пациентов</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-9 col-lg-9">
        <ul class="footer-menu">
          <li><a href="#">О портале</a></li>
          <li><a href="#">Контакты</a></li>
          <li><a href="#">Реклама</a></li>
        </ul>
      </div>
      <div class="col-3 d-block d-lg-none text-right">
        <%= image_tag "12.svg", alt: '' %>
      </div>
      <div class="col-12 col-lg-3">
        <ul class="footer-social">
          <li><%= link_to image_tag('facebook.svg'), mednews_path, alt: '' %></li>
          <li><%= link_to image_tag('vk.svg'), mednews_path, alt: '' %></li>
          <li><%= link_to image_tag('odnoklassniki.svg'), mednews_path, alt: '' %></li>
          <li><%= link_to image_tag('twitter.svg'), mednews_path, alt: '' %></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-9">
        <p>Медицинский портал medportal.ru. <br>Адрес: Россия, 119270, Москва, Лужнецкая набережная, д. 2/4, стр.1, этаж 2, помещение I, комната 18 </p>
        <p class="mb-0">© 1998—2019 Все права защищены. Любое использование материалов допускается только с письменного согласия редакции.</p>
      </div>
      <div class="col-lg-3 d-none d-lg-block text-right">
        <%= image_tag "12.svg", alt: '' %>
      </div>
    </div>
  </div>
</footer>